# Generated by Django 5.1 on 2024-08-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="image/", verbose_name="Фото")),
            ],
            options={
                "verbose_name_plural": "Фотография",
            },
        ),
        migrations.AddField(
            model_name="settings",
            name="logo",
            field=models.ImageField(
                default=1, upload_to="image/", verbose_name="Логотип"
            ),
            preserve_default=False,
        ),
    ]
