# Generated by Django 5.1 on 2024-08-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_cryptobit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                ("descriptions", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name_plural": "Настройка криптобит",
            },
        ),
        migrations.CreateModel(
            name="ExpertsFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="image/", verbose_name="Фото")),
                ("title", models.CharField(max_length=155, verbose_name="Имя")),
                ("descriptions", models.TextField(verbose_name="Ноправление")),
                ("facebook", models.URLField(verbose_name="Укжите ссылку на facebook")),
                ("chtoto", models.URLField(verbose_name="Укжите ссылку на chtoto")),
                ("twitter", models.URLField(verbose_name="Укжите ссылку на twitter")),
            ],
            options={
                "verbose_name_plural": "Настройка экспертов",
            },
        ),
        migrations.AlterField(
            model_name="cryptobit",
            name="descriptions",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="cryptobit",
            name="title2",
            field=models.CharField(max_length=155, verbose_name="Заголовок2"),
        ),
    ]
