# Generated by Django 5.1 on 2024-08-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_experts_expertsfoto_alter_cryptobit_descriptions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(auto_created=True, verbose_name="Дата")),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                ("descriptions", models.TextField(verbose_name="Описание")),
                ("order", models.CharField(max_length=155, verbose_name="порядок")),
                ("number", models.CharField(max_length=155, verbose_name="номер")),
            ],
            options={
                "verbose_name_plural": "Настройка истории",
            },
        ),
        migrations.AlterModelOptions(
            name="experts",
            options={"verbose_name_plural": "Настройка рядом с экспертами"},
        ),
    ]
