# Generated by Django 5.1 on 2024-08-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="image/", verbose_name="Фото проект"),
                ),
            ],
            options={
                "verbose_name_plural": "Фотография проект",
            },
        ),
        migrations.AddField(
            model_name="about",
            name="descriptions_project",
            field=models.TextField(default=1, verbose_name="Описание проекта "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="title_project",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовок проекта"
            ),
            preserve_default=False,
        ),
    ]
