# Generated by Django 5.1 on 2024-08-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_projectfoto_about_descriptions_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlesFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(auto_created=True, verbose_name="Дата")),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                ("descriptions", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(upload_to="image/", verbose_name="Фото cтатьи"),
                ),
            ],
            options={
                "verbose_name_plural": "Настройка статьи",
            },
        ),
    ]
