# Generated by Django 5.1 on 2024-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_articlesfoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                ("descriptions", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="team/")),
            ],
            options={
                "verbose_name_plural": "команда",
            },
        ),
    ]
