# Generated by Django 5.1 on 2024-08-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name_plural": "Настойка инвистиции"},
        ),
    ]
