# Generated by Django 5.1 on 2024-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(upload_to="banner/", verbose_name="баннер"),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                (
                    "title_cryptobit",
                    models.CharField(
                        max_length=155, verbose_name="Заголовок криптобита"
                    ),
                ),
                ("descriptions", models.TextField(verbose_name="Описание криптобита")),
                (
                    "foto_cryptobit",
                    models.ImageField(
                        upload_to="foto/", verbose_name="фото криптобита"
                    ),
                ),
                (
                    "title_project",
                    models.CharField(max_length=155, verbose_name="Заголовок проекта"),
                ),
                (
                    "descriptions_project",
                    models.TextField(verbose_name="Описание проекта "),
                ),
            ],
            options={
                "verbose_name_plural": "Настройка статьи",
            },
        ),
    ]
