# Generated by Django 5.1 on 2024-08-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
