# Generated by Django 5.1 on 2024-08-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0002_delete_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="заголовок")),
                ("image", models.ImageField(upload_to="image/", verbose_name="фото")),
                ("date", models.DateField(auto_now_add=True, verbose_name="дата")),
            ],
            options={
                "verbose_name_plural": "Настройка блога",
            },
        ),
    ]
