# Generated by Django 5.1 on 2024-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="banner",
            field=models.ImageField(
                default=1, upload_to="banner/", verbose_name="баннер"
            ),
            preserve_default=False,
        ),
    ]
