# Generated by Django 5.1 on 2024-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blog_descriptions_blog_title_cryptobit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="заголовок")),
                ("image", models.ImageField(upload_to="image/", verbose_name="фото")),
                ("date", models.DateField(auto_now_add=True, verbose_name="дата")),
                ("descriptions", models.TextField(verbose_name="Описание криптобита")),
            ],
            options={
                "verbose_name_plural": "Настройка блога",
            },
        ),
    ]
